### ISSUE TITLE
Thrust SFX in Asteroids can't be muted

### ISSUE THREAD

**Issue by d-klx** [retrowars/retrowars#104]
First of all: Thanks so much for the effort you put into the games!
I love the app and enjoy it very much!

I think this is just a small bug, but somehow annoying, when listening to a podcast or music at the same time.

**Describe the bug**
There is some sound effect playing at the end of each use of the thrust although sound effects are muted.

**To Reproduce**
1. Mute sound effects
2. Play Asteroids and use the thrust

**Expected behavior**
No sound

**Comment by ig9000** [comment]
I noticed this too. It seems that the "fade out" part of the thruster envelope is always played as a ramp from 100%, ignoring the volume setting (or muting) for the sound fx.

**Comment by pserwylo** [comment]
Good pickup, I'll get that fixed up, it must be annoying!

**Comment by d-klx** [comment]
> @d-klx: Do you happen to also see the same behavior of sounds not initially playing as described in #105? If not, it may just be related to my specific phone.

@ig9000: Yes I have the same experience on my Pixel phone.

**Comment by pserwylo** [comment]
Okay, v0.31.2 tagged and ready to be built/released by F-Droid within approx a week.

I must admit, the reason I didn't catch this is because I'm one of those lazy Asteroids players who camps in the centre of the screen and never-ever-ever moves anywhere for fear of getting disoriented and crashing into something :)
