### ISSUE TITLE
0.31.1 release fails to play sound fx first time they are triggered

### ISSUE THREAD

**Issue by ig9000** [retrowars/retrowars#105]
**Describe the bug**
Sound effects seem to not actually play the first time they should be triggered, but do play on subsequent triggers. This results in some sounds, such as the snake crashing, never being played at all. This only happens on my phone, using the 0.31.1 release from f-droid. It doesn't happen with the Java build I'm using for sound development, although when using that I do notice via the console that the sounds seem to be loaded "just in time" on first use, rather than when game initializes, so my guess is it's probably related to that not happening fast enough on Android.

**To Reproduce**
Start a game, notice first time firing (for example) in asteroids doesn't produce sound, first asteroid hit doesn't produce sound, etc.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10
 - Android Version: 9

**Comment by pserwylo** [comment]
Yes, you are right, I've noticed the same. 

And you are also right that sounds are loaded just in time, which is a terrible way to do things. I did it for the initial prototype so that we could get moving, but never revisited. They are also not disposed of correctly, which is also bad. In fact I felt guilty when you were researching that using Android's native sampling rate improves performance, knowing full well that this performance gain is dwarfed by my lazy coding here!

I do have some ideas on how to make this work, and the libgdx framework being used is helpful here too. An initial cut will forgoe a formal loading screen in preference to just a black screen (hoping the loading of all sound effects only takes a brief moment - the music is already streamed appropriately and never fully loaded into memory). A future version will implement a proper loading screen if required.

**Comment by ig9000** [comment]
> And you are also right that sounds are loaded just in time, which is a terrible way to do things.

It seemed a little odd when I noticed it with the Java build, but it didn't seem to cause any real problems there. :shrug: 

> In fact I felt guilty when you were researching that using Android's native sampling rate improves performance, knowing full well that this performance gain is dwarfed by my lazy coding here!

Haha, well, that was stuff I'd been wondering about for a while, but had't yet had a good reason to look into. My main concern here was that the sample rates of the resources not become a baked-in problem for whatever eventual optimizations may or may not happen. As it turns out, the amount of latency in the last release wasn't really objectionable to me (and I probably object to it more than most people).

> hoping the loading of all sound effects only takes a brief moment

My thought would be to load them when starting each game, and use that half a second or whatever to display the control positions so the player can orient themselves before the action starts. As things are, some games start a little abruptly for my slow brain, tbh.

I've been meaning to comment on the new releases, but got kind of busy with life for a while. The other thing I noticed was that the looping of the music isn't gapless (I couldn't really tell with the previous fade-out versions). Hopefully there's a fix for this that still allows for streaming. There's a way to indicate looping in Android ringtones, for instance, using OGG metadata, and [this post](https://stackoverflow.com/questions/12834727/android-loop-true-how-to-avoid-mediaplayer-looping-audios-with-this-metadat) suggests that it applies to the sound player generally... but I haven't looked further into that yet.

All in all, the addition of sounds feels like a great improvement, and I'm looking forward to playing with it some more. If you want to close #41 now, I can create individual issues for uploading new sounds, if that makes more sense.

**Comment by pserwylo** [comment]
Okay, fixed in [v0.31.3](https://github.com/retrowars/retrowars/releases/tag/0.31.3) tagged and ready for F-Droid to build and release.

Things it *does*:
 * Load all sounds for a specific game prior to play starting, and does so politely without locking up the system
 * Correctly dispose of sounds once done
 * Still plays the sounds themselves on a background thread (because when playing lots of concurrent sounds like in Tempest, it slowed the game down even though the sounds were loaded from disk already).

Things it does *not* do:
 * Show any feedback about loading (in practice, it only takes a fraction of a second before being ready). In the future, I think we should have a proper loading experience which does as you've recommended - show the on screen controls, and perhaps some hint as to what to expect when the game starts.
