### ISSUE TITLE
Logo/Icon proposal

### ISSUE THREAD

**Issue by Kriubby** [retrowars/retrowars#19]
Hello!

Hey! I'm a Graphic Designer and ! want to improve my skills. I found this game in F-droid and I loved the idea and the game.
 
I'm interested in collaborating with this project by delivering a free logo proposal. Should I create an Issue or a Pull Request? And if you want to improve some specific art, you can tell me and I could try it!

Thank you,
Mateus Lucena

**Comment by pserwylo** [comment]
Hi, thanks for your kind words and offer of assistance. I was just about to respond to your email but am more than happy for discussions like this to take place here.

Regarding graphic design contributions... yes - please post these as issues in GitHub so that the community can discuss together.

A few thoughts:
* I like the graininess and pixel-ness of the current icon (though not a hard requirement)
* I *dislike* that it doesn't show any of the following:
  * More than one type of retro game - currently just asteroids (doesn't need all, but I wonder if there is a way to pick a couple of popular games and get them in somehow)
  * Multiplayer - currently looks like single player asteroids

**Comment by pserwylo** [comment]
Hi, I'm going to close this for now to clean up the issues list, but please feel free to jump back online if you have any further feedback.
