### ISSUE TITLE
Translations can't push to repo

### ISSUE THREAD

**Issue by comradekingu** [retrowars/retrowars#65]
I added nb_NO and it locked the translation component I added.
If you add "kingu" in https://hosted.weblate.org/access/retrowars/#users I can have a look. :)

**Comment by pserwylo** [comment]
Thanks as always @comradekingu !

Added. 

I got most the way through setting it up then had to go to bed. I will take another look in the next day or two, but please feel free to poke around in th meantime. 

Please be aware most strings are hardcoded right now. As soon as weblate is configured I'll go update the app to make it translateable as a matter of priority. 

Cheers.

**Comment by pserwylo** [comment]
Okay, needed to add the @weblate user to the repo with permission to write. That is now done, and your changes have been brought in. I'll now go start work on finding each string in the game and making it translateable, as well as documenting Weblate to communicate specific strings which are just for a little bit of fun and translators should have fun with translating rather than translating literally. Will also add some screenshots to Weblate.

**Comment by comradekingu** [comment]
@pserwylo Thanks for fixing it :) My translation made it in.
I changed the license of the metadata from "GPLv3-only" to "GPLv3-or-later" like the other component.
