### ISSUE TITLE
Screensaver and Live Wallpaper

### ISSUE THREAD

**Issue by JM480** [retrowars/retrowars#75]
I think these games could look pretty cool as a screensaver or live wallpaper.

**Comment by pserwylo** [comment]
Thanks @JM480 - I love the thought and kind of agree, however it is out of scope for what I have time to work on sorry. I'll close this issue because I personally don't have any intention of implementing it, but more than happy to help out with anyone else who has the desire and time to do so. If so, we can re-open this and p
