### ISSUE TITLE
Make finger guiding viable in Breakout

### ISSUE THREAD

**Issue by Mormamu** [retrowars/retrowars#79]
**Is your feature request related to a problem? Please describe.**
After playing a few games of Breakout I came to the quick realization that unlike the other games that have on-screen buttons, this game was made with the intention to have the player drag their finger across the screen to guide the paddle. At first I was ok playing like this however some things became very apparent.

1) The paddle had a set speed.
2) The paddle's set speed was way to slow to follow my finger.

This is frustrating as when the ball is on the other side of the screen i would instinctively flick over to it but the paddle is unable to keep up making me lose lives.

**Describe the solution you'd like**
I think that increasing the speed so that it can accurately track the player's finger even at high speeds.

**Describe alternatives you've considered**
Currently the way I play breakout is by having my thumbs at the edges of the screen and tapping to move the paddle sort of like having pseudo buttons. I think it would be cool to have this control scheme inplemented into the game as an extra control layout in the options menu.

**Comment by pserwylo** [comment]
Thanks for the feedback. I agree. The first version I tried had an on-screen controller like others with left + right buttons. I then changed it to dragging based on some arbitrary preference. I quickly noticed after releasing v0.28.0 that my finger obscured the paddle completely to the point it was too hard to play. This resulted in v0.28.1 which will be released by F-Droid soon that moves the paddle up a little bit.

I'll keep this ticket open though, because I also want to provide players such as yourself the option to use onscreen buttons instead of dragging.

**Comment by Mormamu** [comment]
Thank you! Honestly I like the work you're putting into this project and it made me so happy to see Breakout being implemented since it was a game I used to play as a kid, so I wish you the best for the future of this project.

**Comment by pserwylo** [comment]
Appreciate the kind words. Makes working on these things all the more fun when I see that other people enjoy them as much as I do.

**Comment by pserwylo** [comment]
Work in progress, but probably not far off:

https://user-images.githubusercontent.com/248565/169696559-d356eddd-695a-46e8-8432-6cded005d4ec.mp4

**Comment by pserwylo** [comment]
On screen controller [added in v0.28.3](https://github.com/retrowars/retrowars/releases/tag/0.28.3) to be built and released by F-Droid over the next week or so.
