### ISSUE TITLE
Suggestion for game in beta testing?

### ISSUE THREAD

**Issue by Bruhmonster** [retrowars/retrowars#84]
Make it so that at the start it's slower and gradually gets faster, as, well as space out the bricks slightly more to allow to cool combos in the bricks behind, while leaving the other bricks in front intact.

**Comment by pserwylo** [comment]
Thanks for your input. I have a couple of clarifying questions...

**Regarding the speed**

Firstly, I assume you are referring to the ball speed. This does increase in pace as you eliminate more bricks already, but it is easy to change. The maximum speed it will increase currently is [1.3x the original speed](https://github.com/retrowars/retrowars/blob/master/core/src/com/serwylo/retrowars/games/breakout/BreakoutState.kt#L21) and this occurs after breaking [20 bricks](https://github.com/retrowars/retrowars/blob/master/core/src/com/serwylo/retrowars/games/breakout/BreakoutState.kt#L19). 

Are you suggesting to increase the range of speed because this change is not noticeable enough? Or purely do drop the initial speed to make it a little bit easier when first starting?

**Regarding spacing of bricks**

In the spirit of keeping close to one of the original versions, would moving the group of bricks down (but keeping them closely spaced) help address this? In this recording of the Atari 2600 version, you can see the ball getting "stuck" above and combo-ing into multiple bricks once the player broke through:

https://youtu.be/Cr6z3AyhRr8?t=114

**Comment by pserwylo** [comment]
Here is a quick example - It is immediately more fun to me when we drop the blocks a little lower:


https://user-images.githubusercontent.com/248565/169664396-812908ce-d8a1-4c96-9dd2-8e210263a272.mp4

**Comment by pserwylo** [comment]
Still looking forward to your feedback @Bruhmonster, but in the meantime I've tried to tackle these issues in an upcoming release [v0.28.2](https://github.com/retrowars/retrowars/releases/tag/0.28.2). When that hits F-Droid, have a play and let me know what you think.

**Comment by Bruhmonster** [comment]
> Thanks for your input. I have a couple of clarifying questions...
> 
> **Regarding the speed**
> 
> Firstly, I assume you are referring to the ball speed. This does increase in pace as you eliminate more bricks already, but it is easy to change. The maximum speed it will increase currently is [1.3x the original speed](https://github.com/retrowars/retrowars/blob/master/core/src/com/serwylo/retrowars/games/breakout/BreakoutState.kt#L21) and this occurs after breaking [20 bricks](https://github.com/retrowars/retrowars/blob/master/core/src/com/serwylo/retrowars/games/breakout/BreakoutState.kt#L19).
> 
> Are you suggesting to increase the range of speed because this change is not noticeable enough? Or purely do drop the initial speed to make it a little bit easier when first starting?
> 
> **Regarding spacing of bricks**
> 
> In the spirit of keeping close to one of the original versions, would moving the group of bricks down (but keeping them closely spaced) help address this? In this recording of the Atari 2600 version, you can see the ball getting "stuck" above and combo-ing into multiple bricks once the player broke through:
> 
> https://youtu.be/Cr6z3AyhRr8?t=114

What I meant by dropping the speed is definitely meaning to have the start range be much slower, I think it would make it so the start is easy and right now if Im' not paying full attention to the game I'll instantly die and get distracted. Another thing I;ve noticed is that something if you hit the ball with the sides of the paddle, it will instantly die and sometimes it isn;t clear if it will hit the sides or not so making the paddle circular at the ends could help with that.

**Comment by pserwylo** [comment]
Okay, still a little fast when the game starts, but I've gotten some feedback from my friends that once you die a couple of times, then it isn't so bad ;). Will keep as is for now, but please feel free to continue to post here or log a new issue if it feels like it is particularly problematic. Thanks again for your interest!
