### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by AHOHNMYC** [retrowars/retrowars#95]
Hey, guys! I've translated your great project to Russian on Weblate. Please, add this language into game :з

**Comment by pserwylo** [comment]
Thank you so much for your contribution @AHOHNMYC. I will most certainly make the time to incorporate your translation, but a word of warning that it does require generating a new set of fonts - the current font in use only has Latin characters. Fear not, I have already completed this for a similar game https://github.com/beat-feet/beat-feet and so can just port that code, but it will still take a few weeks to find the time. I'll let you know where once it is enabled!

**Comment by AHOHNMYC** [comment]
Nice! Ping me if I in any way can help with fonts/Cyrillic glyphs and anything connected with :-)

**Comment by pserwylo** [comment]
Thanks @AHOHNMYC. One thing that would be helpful is to double check whether the fonts look okay in the game [Beat Feet](github.com/beat-feet/beat-feet) ([F-Droid link](https://f-droid.org/packages/com.serwylo.beatgame/)). The way it works is:

* Use [bitmap fonts from Kenney.nl](https://kenney.nl/assets/kenney-fonts) if the language uses Latin glyphs (preferred approach because it fits with the pixelated style of the game).
* If other characters are required, use [Google Noto Mono](https://fonts.google.com/noto/specimen/Noto+Sans+Mono), as this is a font which has extremely broad coverage across a large number of languages around the world - which means we don't need to keep making exceptions as new languages are onboarded).
* Instead of including the entire font and all of its glyphs (which need to be saved in various font sizes and generated as images), we instead use a script to parse all of the `messages` files and gather all of the characters used for each translation. This means the script needs to be run each time translations are added, but it has shown to work quite well in practice.

Some feedback I'm after:
 * How strange is it having a non-bitmap font (smooth rounded edges, etc) in a game that is trying to be retro/pixelated?
 * Any other thoughts?

**Comment by pserwylo** [comment]
So far so good. Font glyphs are working as expected. Now I will just spend a little time making sure that the font sizes are appropriate for this Google Noto font (currently a little big) and that text wraps appropriately on each screen:

![image](https://user-images.githubusercontent.com/248565/173060545-6d4dca69-2c57-4dc9-8a66-6385c8ec2171.png)

![image](https://user-images.githubusercontent.com/248565/173060577-40d972e5-c9b6-4c63-ba76-e67c1b07accf.png)

![image](https://user-images.githubusercontent.com/248565/173060658-000a183c-d09c-4272-93f4-e14dcf85fd02.png)

![image](https://user-images.githubusercontent.com/248565/173060691-9e083a07-c5b8-4cdc-928a-25d0aa7fd73c.png)

![image](https://user-images.githubusercontent.com/248565/173060724-0a7e8606-33fc-4e3d-aba1-56658fb7209f.png)

![image](https://user-images.githubusercontent.com/248565/173060763-cc088765-3a88-4f6f-bca0-8731709d3a0d.png)

**Comment by SecularSteve** [comment]
Speaking of Cyrillic, please make sure the same can apply for the Serbian Translation.

It uses a more basic Cyrillic Alphabet with slight region-specific additional letters.

**Comment by pserwylo** [comment]
Thank you kindly for the offer, but this is all scripted. If you're interested in the kotlin code responsible for this, you can see it here:

https://github.com/retrowars/retrowars/commit/64c008d23df0ee748636d551e0ad7f08d5205130#diff-0bb056a6b3ea53834dd5e859e8d0989360c6cfae3107ec25bae8b1f6a151b2c5R54-R75

I'm just going to do some final testing, then I'll tag v0.31.0 to be built and released by F-Droid (will take a few days, to a week). Once you see that version become available, I'd love to hear any feedback you may have!

**Comment by pserwylo** [comment]
[0.31.0 is now tagged](https://github.com/retrowars/retrowars/releases/tag/0.31.0) and waiting for F-Droid to build.

I've intentionally pixelated the largest font size in the game hoping to get a retro feel, but was unsuccessful in doing so with smaller fonts without making them unreadable. If this seems weird, please let me know and I can remove the pixelation on the larger font and revert to the smoother version.
